### ISSUE TITLE
Contact form error

### ISSUE THREAD

**Issue by adamsingle** [ireade/openwriter#1]
I followed the instructions for setting up the Contact form, but when I try to submit it I get an error "Method Not Allowed - The method is not allowed for the requested URL"

**Comment by ireade** [comment]
I will look into that asap

**Comment by adamsingle** [comment]
Awesome, thank you. For some reason I also can't get any static pages to show up as links like in your example. I have to manually add /contact to the url to get to that page for example.

**Comment by ireade** [comment]
I fixed the contact form. The issue was that Ghost no longer allows themes to access the author/blog's email for security reasons. So, you have to manually add your email. I updated the README with instructions on how to do this.

For the navigation, you have to add new links manually in Settings > Navigation. I don't think there is a way to automatically add new pages to the navigation.

Could you let me know if everything works for you?

**Comment by adamsingle** [comment]
Thank you for the fast response, I didn't realise that about the navigation. That was easy to fix. That also solved the contact form issue. Thank you again for getting back to me so quickly

**Comment by ireade** [comment]
You're welcome, glad to help :)
